
[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "a032972e28060ca4f5644acffae3dfc268cc09db"

[[constraint]]
  name = "google.golang.org/api"
  revision = "65a46cafb132eff435c7d1e0f439cc73c8eebb85"
